/* THROWAWAY PROTOTYPE — three navigation structures on ?variant=A|B|C.
 * Memory-only sample state. Decisions remain in the linked Wayfinder tickets.
 * Fixed date keeps review examples reproducible; this is not a calendar engine. */
const TODAY='2026-09-08', JOINED='2026-08-01';
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const regions=['厨房烹饪','客厅公共区','卧室衣物','卫浴清洁','阳台宠植','综合事务'];
const variants={A:'四栏直达',B:'家庭首页',C:'任务优先'};
const modules=[['tasks','⌂','任务大厅'],['balance','⚖','协作天平'],['journal','♡','动态打卡簿'],['wishes','✧','心愿集市']];
const templates=[
 {source:'dishes',name:'清洗餐后碗筷',desc:'清洗碗筷并擦净水槽。',region:0,points:20,freq:'daily',first:TODAY},
 {source:'shoes',name:'整理玄关鞋柜',desc:'归位鞋子，擦拭可见灰尘。',region:1,points:30,freq:'weekly',first:'2026-09-13'},
 {source:'linen',name:'换洗床上四件套',desc:'更换、清洗并晾晒床品。',region:2,points:40,freq:'weekly',first:'2026-09-13'},
 {source:'bath',name:'清洁浴室地面',desc:'刷洗地面与排水口。',region:3,points:40,freq:'weekly',first:'2026-09-12'},
 {source:'plant',name:'照料阳台植物',desc:'检查土壤，按植物需要浇水；适用于有绿植的家庭。',region:4,points:20,freq:'interval',first:TODAY,every:3},
 {source:'filter',name:'清洗空调滤网',desc:'拆洗可水洗滤网并充分晾干。',region:5,points:80,freq:'monthly',first:'2026-09-30',day:31,every:3}
];
let variant=new URLSearchParams(location.search).get('variant')||'B';if(!variants[variant])variant='B';
let S, page='tasks', taskView='current', journalView='all', wishView='catalog', month='2026-09', walletPerson='me', selected=new Set(), filters={q:'',region:'',owner:'',freq:''}, activeScenario='paired', addMode='presets', pending=null, draft=null, toastTimer;
function dateLabel(d){return d?`${Number(d.slice(5,7))}月${Number(d.slice(8,10))}日`:'未填完成日期'}
function plusDays(d,n){const t=new Date(d+'T00:00:00Z');t.setUTCDate(t.getUTCDate()+Number(n));return t.toISOString().slice(0,10)}
function weekDay(d){return new Date(d+'T00:00:00Z').getUTCDay()}
function nextDate(t,start=t.plan){if(t.freq==='once')return null;if(t.freq==='daily')return plusDays(start,1);if(t.freq==='interval')return plusDays(start,t.every||3);if(t.freq==='weekly'){const days=t.weekdays||[weekDay(start)];for(let i=1;i<=7;i++){const d=plusDays(start,i);if(days.includes(weekDay(d)))return d}}const d=new Date(start+'T00:00:00Z');d.setUTCMonth(d.getUTCMonth()+(t.every||1),1);const end=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate();d.setUTCDate(Math.min(t.day||Number(start.slice(8)),end));return d.toISOString().slice(0,10)}
function person(p){return p==='me'?`${S.me}（我）`:p==='partner'?S.partner:p==='pool'?'待认领':'等待伴侣确认'}
function freqLabel(t){return({daily:'每天',weekly:'每周 '+(t.weekdays||[weekDay(t.plan||t.first)]).map(n=>'日一二三四五六'[n]).join('、'),interval:`每隔 ${t.every||3} 天`,monthly:`每隔 ${t.every||1} 个月 · ${t.day||31} 日`,once:'一次性'})[t.freq]}
function seed(){let tasks=[
 {id:1,source:'dishes',name:'清洗餐后碗筷',desc:'碗筷洗净，顺手擦净水槽。',region:0,points:20,freq:'daily',owner:'me',plan:TODAY,exec:TODAY,mode:'me',fixed:true},
 {id:2,source:'linen',name:'换洗床上四件套',desc:'换下、清洗并晾晒床品。',region:2,points:40,freq:'weekly',owner:'partner',plan:'2026-09-06',exec:'2026-09-06',mode:'rotate',fixed:true,roundOwner:'partner',weekdays:[0]},
 {id:3,source:'hood',name:'清洗抽油烟机滤网',desc:'拆下滤网清洁油污，晾干后装回。',region:0,points:80,freq:'weekly',owner:'pool',plan:'2026-09-13',exec:'2026-09-13',mode:'pool',fixed:false,weekdays:[0]},
 {id:4,source:'plant',name:'照料阳台植物',desc:'检查土壤，按需要浇水。',region:4,points:20,freq:'interval',every:3,owner:'pool',plan:TODAY,exec:TODAY,mode:'pool',fixed:true},
 {id:5,source:null,name:'整理搬家纸箱',desc:'拆平空纸箱并分类回收。',region:5,points:30,freq:'once',owner:'me',plan:'2026-09-07',exec:'2026-09-07',mode:'me',fixed:true},
 {id:6,source:'window',name:'擦拭客厅窗台',desc:'擦去窗台积尘。',region:1,points:30,freq:'weekly',owner:'me',plan:TODAY,exec:TODAY,mode:'me',fixed:true,status:'paused',closed:'暂停关闭',weekdays:[2]}
 ];tasks=tasks.map(t=>({...t,base:{...t},status:t.status||'active',next:nextDate(t),history:[]}));
 const records=[
 {id:101,taskId:90,name:'清洁浴室地面',owner:'me',points:60,plan:'2026-09-07',actual:'2026-09-07',submitted:'2026-09-07',active:true,note:'地面清爽了，心情也跟着轻一点。',thanks:'谢谢你帮忙收好了毛巾。',heart:true,trace:[]},
 {id:102,taskId:91,name:'准备晚餐',owner:'partner',points:60,plan:'2026-09-07',actual:'2026-09-07',submitted:'2026-09-07',active:true,note:'今天试了新的番茄意面。',heart:false,trace:[]},
 {id:103,taskId:92,name:'整理衣柜换季衣物',owner:'me',points:100,plan:'2026-09-06',actual:'2026-09-06',submitted:'2026-09-06',active:true,note:'把薄外套放到容易拿的位置。',heart:true,trace:[]},
 {id:104,taskId:93,name:'清洁卫浴镜面',owner:'partner',points:40,plan:'2026-09-05',actual:'2026-09-05',submitted:'2026-09-05',active:true,note:'',heart:false,trace:[]},
 {id:105,taskId:94,name:'收纳清洁用品',owner:'me',points:40,plan:'2026-08-31',actual:'2026-08-31',submitted:'2026-08-31',active:true,note:'',heart:false,trace:[]}
 ];
 return{family:'梧桐小家',status:'active',me:'小满',partner:'阿宁',single:false,records,tasks,wishes:[
 {id:1,source:'massage',name:'肩颈按摩 20 分钟',desc:'找个舒服的位置，放松一下肩颈。',price:60,provider:'partner',status:'open'},
 {id:2,source:'breakfast',name:'周末做一次早餐',desc:'做一份你喜欢的早餐，一起慢慢吃。',price:120,provider:'me',status:'pending'},
 {id:3,source:'quiet',name:'两小时免打扰时光',desc:'留出一段自己的时间。',price:80,provider:'partner',status:'pending'}
 ],orders:[{id:1,wishId:99,name:'晚餐独家指定权',desc:'今晚的菜由你来选，一起好好吃饭。',price:60,provider:'partner',buyer:'me',status:'pending',note:'周末一起安排',trace:[],removed:true}],ledger:[],wallet:{me:0,partner:0},missed:[{id:801,name:'整理玄关鞋柜',points:30,plan:'2026-08-30',originalOwner:'partner',status:'missed'}],notices:[],celebrations:0,invitation:'none'};
}
function post(owner,amount,title,reason=''){S.wallet[owner]+=amount;S.ledger.unshift({owner,amount,title,reason,balance:S.wallet[owner],date:TODAY})}
function reset(scenario=activeScenario){activeScenario=scenario;addMode='presets';pending=null;draft=null;selected.clear();filters={q:'',region:'',owner:'',freq:''};taskView='current';journalView='all';wishView='catalog';month='2026-09';S=seed();
 for(const r of [...S.records].reverse()){post(r.owner,r.points,r.name);S.ledger[0].date=r.submitted}post('me',-60,'兑换：晚餐独家指定权');
 if(['first','invite','expired','single','empty'].includes(scenario)){S.records=[];S.tasks=[];S.orders=[];S.wishes=[];S.ledger=[];S.wallet={me:0,partner:0};S.missed=[];S.single=scenario!=='empty';if(['first','invite','expired'].includes(scenario))S.status='none';S.invitation=scenario==='invite'?'valid':scenario==='expired'?'expired':'none'}
 if(scenario==='disabled'){S.status='disabled';S.notices=['2026 年 9 月 8 日 10:30 · 平台暂停家庭协作','原因：检测到异常操作频率，暂时停用。成员关系与历史保留。']}
 if(scenario==='archived')archive();
 if(scenario==='negative'){S.orders[0].status='completed';S.orders[0].price=180;post('me',-120,'兑换补足至 180 分');const r=S.records.find(r=>r.id===105);r.active=false;r.trace.push('本人撤销：重复记录');post('me',-40,'撤销：收纳清洁用品','重复记录')}
 S.readError=scenario==='read-error';page=S.status==='none'?(S.invitation==='none'?'welcome':'join'):(variant==='B'?'home':'tasks');$('#scenario').value=scenario;$('#failure').value='none';closeModal();render();}
function readonly(){return S.status!=='active'}
function btn(label,action,id='',cls='',disabled=false){return `<button type="button" data-action="${action}"${id!==''?` data-id="${esc(id)}"`:''} class="${cls}"${disabled?' disabled':''}>${label}</button>`}
function empty(title,text,cta=''){return `<div class="empty"><div class="empty-mark">⌂</div><h3>${title}</h3><p>${text}</p>${cta}</div>`}
function section(title,cta=''){return `<div class="section"><h3>${title}</h3>${cta}</div>`}
function ro(){return readonly()?`<div class="notice">${S.status==='archived'?'归档历史仅供查看，不能继续协作。':'家庭暂时停用，历史保留；恢复由平台处理。'}</div>`:''}
function go(p){page=p;render();$('.content').scrollTop=0}
function toast(text){$('#toast').textContent=text;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{$('#toast').textContent=''},5000)}
function celebrate(){S.celebrations++;const n=document.createElement('div');n.className='confetti';n.textContent='✦ · ✧ · ✦';document.body.append(n);setTimeout(()=>n.remove(),1100)}
function closeModal(){if($('#modal').open)$('#modal').close()}
function modal(title,body){$('#modal-body').innerHTML=`${btn('×','close','','dialog-close')}<h2 id="modal-title">${title}</h2>${body}<div id="form-error" role="alert"></div>`;if(!$('#modal').open)$('#modal').showModal()}
function error(msg){if($('#modal').open&&$('#form-error'))$('#form-error').innerHTML=`<div class="error">${esc(msg)}</div>`;else toast(msg)}
function confirmAction(title,text,action,id='',label='确认',danger=false){modal(title,`<p>${text}</p>${btn(label,action,id,'full '+(danger?'danger':'primary'))}${btn('再想想','close','','full')}`)}
function transact(fn,opts={}){if(readonly()&&!opts.allow){error('当前家庭不可执行这项操作。');return}if(pending){error('请先确认上一笔提交结果。');return}const failure=$('#failure').value;$('#failure').value='none';if(failure==='failed'){error('本次操作未生效，已保留填写内容。可以重新提交。');return}const result=fn();if(result===false)return;
 closeModal();if(failure==='unknown'){pending={message:result||'操作已完成',celebrate:!!opts.celebrate};render();modal('正在确认提交结果',`<p>暂时未收到明确结果，请先查询本次处理结果。查询不会发起第二笔操作。</p>${btn('查询本次结果','query-result','','primary full')}`)}else{render();if(opts.celebrate)celebrate();toast(result||'操作已完成')}renderState();}
function renderState(){$('#state').textContent=JSON.stringify({方案:variant,页面:page,家庭:S.status,单人:S.single,可处理事项含最近未来:S.tasks.filter(t=>t.status==='active'&&!t.completed&&!t.closed).length,有效完成:S.records.filter(r=>r.active).length,可用积分:S.wallet,待兑现:S.orders.filter(o=>o.status==='pending').length,撒花次数:S.celebrations,待确认结果:!!pending},null,2)}
function render(){const titles={tasks:'任务大厅',balance:'协作天平',journal:'动态打卡簿',wishes:'心愿集市',settings:'家庭设置',wallet:'积分明细',templates:'添加家务',home:'今天，也一起照顾家',welcome:'欢迎来到家务搭档',join:'一起组成一个家',history:'已归档家庭',wishTemplates:'选一份小心愿',calendar:'日期与恢复说明'};
 let nav='';if(S.status!=='none'){if(variant==='A')nav=`<nav class="tabs">${modules.map(([p,s,t])=>btn(`<span class="tab-symbol">${s}</span>${t}`,'nav',p,page===p?'active':'')).join('')}</nav>`;else if(variant==='B')nav=`<nav class="tabs" style="grid-template-columns:1fr 1fr">${btn('<span class="tab-symbol">⌂</span>家庭首页','nav','home',page==='home'?'active':'')}${btn('<span class="tab-symbol">⚙</span>家庭设置','nav','settings',page==='settings'?'active':'')}</nav>`;else nav=`<div class="journey-nav">${btn('查看贡献','nav','balance')}${btn('翻看动态','nav','journal')}${btn('心愿与待兑现','nav','wishes')}</div>`}
 const status=S.status==='disabled'?`<div class="banner">家庭暂时停用<br>${S.notices.map(esc).join('<br>')}</div>`:S.status==='archived'?'<div class="banner archive">已归档家庭 · 历史只读 · 不可恢复</div>':'';
 const top=S.status==='none'?'':page==='tasks'&&variant==='B'?btn('＋ 添加家务','add-task','','add-task',readonly()):variant==='C'?btn('☰ 模块','menu','','small'):page==='settings'?btn('回到任务','nav','tasks','small'):btn('家庭设置','nav','settings','small');
 const sub=page==='templates'?`<div class="backbar">${btn('← 返回任务大厅','nav','tasks')}</div>`:variant==='B'&&!['home','settings','welcome','join'].includes(page)?`<div class="backbar">${btn('← 家庭首页','nav','home')}</div>`:'';
 const views={tasks:tasksPage,balance:balancePage,journal:journalPage,wishes:wishesPage,settings:settingsPage,wallet:walletPage,templates:templatesPage,home:homePage,welcome:welcomePage,join:joinPage,history:historyPage,wishTemplates:wishTemplatesPage,calendar:calendarPage};
 $('#app').innerHTML=`${sub}<header class="page-head"><div><p class="kicker">${S.status==='none'?'家务搭档':esc(S.family)+' · '+esc(S.me)+'本人账号'}</p><h2>${titles[page]||''}</h2></div>${top}</header>${status}${page==='tasks'&&S.lastCompletion&&!pending&&!readonly()?`<div class="completion-notice" role="status"><div><strong>已完成 · ＋${S.lastCompletion.points} 分</strong><p>${esc(S.lastCompletion.name)}</p></div>${btn('查看记录','view-completion','','small')}${btn('×','dismiss-completion','','small')}</div>`:''}<main class="content">${S.readError?empty('暂时没有加载出来','数据未被清空，重试后可继续查看。',btn('重新加载','retry-read','','primary')):(views[page]||tasksPage)()}</main>${nav}`;
 $('#variant-label').textContent=`${variant} · ${variants[variant]} · ${variant==='B'?'已选导航':'保留对照'}`;renderState();}
function homePage(){return `<div class="hero"><div class="muted">9 月 8 日 · 星期二</div><h3 style="margin-top:10px">一件小事，<br>也是一份照顾。</h3><p>${S.single?'你的付出，已经好好记下。':`和 ${esc(S.partner)}，把生活过得井井有条。`}</p></div><div class="portal">${modules.map(([p,s,t],i)=>btn(`${s}<strong>${t}</strong><small>${['认领和完成今天的家务','看见彼此的每一份付出','把感谢留给对方','用积分交换一份小期待'][i]}</small>`,'nav',p)).join('')}</div>${section('继续处理')}${btn(`${S.orders.filter(o=>o.status==='pending').length} 笔待兑现　→`,'orders','','setting-item')}${btn('管理全部家务　→','all-tasks','','setting-item')}`}
function taskList(){return S.tasks.filter(t=>t.status!=='deleted').filter(t=>taskView==='all'||(t.status==='active'&&(!t.closed||taskView==='future'&&t.freq!=='once')&&(taskView==='future'?(t.exec>TODAY||t.next>TODAY||t.future?.first>TODAY):t.exec<=TODAY))).filter(t=>(!filters.q||(t.name+' '+t.desc).includes(filters.q))&&(!filters.region||t.region===Number(filters.region)-1)&&(!filters.owner||t.owner===filters.owner)&&(!filters.freq||t.freq===filters.freq))}
function tasksPage(){const list=taskList();return `${variant==='C'?'<div class="mini-summary"><span>先找到今天的这件事</span><span>本人账号</span></div>':''}${S.single?`<div class="notice">伴侣还没加入。你可以先安排、认领和打卡。${btn('邀请伴侣','invite','','link full')}</div>`:''}${S.notices.length&&S.status==='active'?`<div class="notice green">${S.notices.map(esc).join('<br>')}</div>`:''}<div class="segments">${[['current','当前待办'],['future','未来预览'],['all','全部家务']].map(([k,v])=>btn(v,'task-view',k,taskView===k?'selected':'')).join('')}</div><p class="muted">${taskView==='current'?'今天要做的，以及仍可处理的逾期事项。':taskView==='future'?'浏览不会固定安排；可操作时先处理当前这一次。':'这里管理长期安排，完成一次不会删除家庭家务。'}</p><input class="search" id="search" aria-label="搜索家务名称和说明" placeholder="搜索家务名称或说明" value="${esc(filters.q)}"><details class="filters"${filters.region||filters.owner||filters.freq?' open':''}><summary>区域 · 负责人 · 周期筛选</summary><div class="filter-fields"><label>区域<select id="filter-region"><option value="">全部区域</option>${regions.map((v,i)=>`<option value="${i+1}"${filters.region==i+1?' selected':''}>${v}</option>`).join('')}</select></label><label>负责人<select id="filter-owner">${[['','全部负责人'],['me',person('me')],...(!S.single?[['partner',person('partner')]]:[]),['pool','待认领']].map(([k,v])=>`<option value="${k}"${filters.owner===k?' selected':''}>${esc(v)}</option>`).join('')}</select></label><label>周期<select id="filter-freq">${[['','全部周期'],['daily','每天'],['weekly','每周'],['interval','每隔 N 天'],['monthly','每隔 N 个月'],['once','一次性']].map(([k,v])=>`<option value="${k}"${filters.freq===k?' selected':''}>${v}</option>`).join('')}</select></label></div>${btn('清除筛选','clear-filters','','link')}</details><div id="task-list">${list.length?list.map(taskCard).join(''):empty(S.tasks.length?'当前没有匹配事项':'从一件家务开始',S.tasks.length?'可以切换视图或清除筛选。':'选择适合你们家的预设，也可以自己创建。',btn(S.tasks.length?'清除筛选':'添加家务',S.tasks.length?'clear-filters':'add-task','','primary',!S.tasks.length&&readonly()))}</div>${variant!=='B'?btn('＋ 添加家务','add-task','','full',readonly()):''}${taskView==='all'?btn('查看日期与恢复说明','nav','calendar','link full'):''}`}
function taskCard(t){if(taskView==='all'){const plan=t.future||t.base||t;return `<article class="task"><div class="row spread"><strong>${esc(plan.name)}</strong><span class="task-score">${plan.points} 分</span></div><p class="task-meta">${regions[plan.region]} · ${freqLabel({...plan,plan:plan.first||plan.plan||t.plan})}<br>${plan.mode==='rotate'?'两人轮流':esc(person(plan.mode))} · ${t.status==='paused'?'已暂停':'安排保留'}</p><div class="plan-preview">本次：${esc(t.name)} · ${dateLabel(t.exec)} · ${t.points} 分 · ${esc(person(t.owner))}<br>${t.completed?'本次已完成':esc(t.closed||'本次待完成')}。${t.future?`后续从 ${dateLabel(t.future.first)} 开始；本次保持不变。`:'修改本次不改变长期安排。'}</div>${btn('管理这项家务','manage-task',t.id,'full')}</article>`}if(taskView==='future'&&t.exec<=TODAY){const future=t.future||{...t,...(t.base||{}),first:t.next,mode:t.mode,firstOwner:t.mode==='rotate'?(t.roundOwner==='me'?'partner':'me'):t.owner};if(!future.first)return '';return `<article class="task"><strong>${esc(future.name)}</strong><p class="task-meta">未来预览 · ${dateLabel(future.first)} · ${freqLabel({...future,plan:future.first})}<br>预期负责人：${esc(person(future.mode==='rotate'?future.firstOwner:future.mode))} · ${future.points} 分</p><div class="plan-preview">${t.closed?'前次关闭结果保留；后续安排沿有效日历继续。':t.completed?'本次已完成，须等原计划日期与执行日期中较晚一天结束，才开放后一期操作。':'当前这次仍需优先处理，下一期预览不会额外产生一条当前待办。'}</div>${btn('查看安排与保留本次','task-detail',t.id,'full')}</article>`}let state=t.status==='paused'?'已暂停':t.completed?'已完成':t.closed||t.exec<TODAY?'逾期':'';if(t.closed)state=t.closed;const active=t.status==='active'&&!t.closed&&!t.completed;let action='';if(active&&!readonly()){action=t.owner==='pool'?btn('认领本次','claim',t.id,'primary'):t.owner==='partner'?btn('本次由我接手','takeover',t.id,'secondary'):btn(t.exec>TODAY?'提前完成本次':'本人打卡','checkin',t.id,'primary');}
return `<article class="task"><div class="task-top"><span class="task-icon">${['◒','⌂','▤','◈','♧','◇'][t.region]}</span><div class="task-main"><span class="task-title">${esc(t.name)}</span><div class="task-meta">${state?`<span class="pill ${state==='逾期'?'warm':''}">${state}</span>`:''}${esc(person(t.owner))}<br>${dateLabel(t.exec)}${t.exec!==t.plan?` · 原定 ${dateLabel(t.plan)}`:''} · ${freqLabel(t)}${taskView==='future'?`<br>${t.fixed?'本次已固定':'尚未固定的未来预览'}`:''}</div></div><span class="task-score">${t.points}<small> 分</small></span></div>${t.future?`<div class="plan-preview">后续：${dateLabel(t.future.first)} 起 · ${freqLabel({...t.future,plan:t.future.first})} · ${t.future.points} 分<br>首位 ${esc(person(t.future.mode==='rotate'?t.future.firstOwner:t.future.mode))}；保留本次不改写。</div>`:''}<div class="task-actions">${btn(taskView==='all'?'管理安排':'详情','task-detail',t.id)}${action}</div></article>`}
function taskDetail(id){const t=S.tasks.find(t=>t.id===+id);if(!t)return;const active=t.status==='active'&&!t.closed&&!t.completed;const action=t.owner==='pool'?['认领这一次','claim','准备承担这次家务时，先认领；实际做完后再打卡。']:t.owner==='partner'?['这一次由我接手','takeover','如果这次由你来做，先接手；只改变本次负责人。']:[t.exec>TODAY?'提前完成这一次':'本人打卡','checkin','实际做完这次家务后，记录完成并获得积分。'];modal(t.name,`<p>${esc(t.desc)}</p><div class="task-facts"><p><span>这次安排</span><strong>${dateLabel(t.exec)}</strong></p><p><span>由谁负责</span><strong>${esc(person(t.owner))}</strong></p><p><span>完成可得</span><strong>${t.points} 分</strong></p></div>${active&&!readonly()?`<div class="task-next"><p class="muted">${action[2]}</p>${btn(action[0],action[1],t.id,'primary full')}</div>${btn('调整这一次','adjust-instance',t.id,'full')}<p class="action-hint">临时改日期、换个人做，或这次不做。</p>`:`<div class="notice">${readonly()?S.status==='archived'?'家庭已归档，这次记录仅供查看。':'家庭暂时停用，这次暂不能操作。':t.completed?'这次已经完成，可在动态打卡簿查看或更正本人的记录。':esc(t.closed||'这项家务已暂停')}</div>`}<details class="task-extra"><summary>查看安排与变更记录</summary><p>区域：${regions[t.region]}<br>原计划：${dateLabel(t.plan)}<br>接续日期：${t.next?dateLabel(t.next):'一次性，无下一期'}<br>${freqLabel(t)} · ${t.fixed?'本次已固定':'未来预览尚未固定'}</p>${t.future?`<p>后续从 ${dateLabel(t.future.first)} 起 · ${freqLabel({...t.future,plan:t.future.first})} · ${t.future.points} 分；本次保持不变。</p>`:''}${t.history.length?`<p>${t.history.map(esc).join('<br>')}</p>`:''}</details>`)}
function adjustInstance(id){const t=S.tasks.find(t=>t.id===+id);if(!t||readonly()||t.completed||t.closed)return;modal('调整这一次',`<p class="muted">${esc(t.name)} · ${dateLabel(t.exec)}。下面的操作都只影响这一次。</p><div class="choice-block">${btn('修改本次安排','edit-once',t.id,'full')}<p>临时改日期、负责人、分值或完成内容。</p></div><div class="choice-block">${btn('这次不做了','skip',t.id,'full')}<p>跳过本次，不获得积分，后面的安排照常。</p></div>${t.owner==='me'&&t.mode==='pool'?`<div class="choice-block">${btn('放回待认领','release',t.id,'full')}<p>已认领但想交还，让家人重新认领这一次。</p></div>`:''}${btn('返回任务详情','task-detail',t.id,'link full')}`)}
function manageTask(id){const t=S.tasks.find(t=>t.id===+id);if(!t)return;const plan=t.future||t.base||t;modal('管理这项家务',`<h3>${esc(plan.name)}</h3><p class="muted">${freqLabel({...plan,plan:plan.first||plan.plan||t.plan})} · ${plan.points} 分 · ${plan.mode==='rotate'?'两人轮流':esc(person(plan.mode))}</p><div class="notice">这里管理以后怎么安排。本次日期或负责人临时有变，请到对应任务详情中调整。</div>${!readonly()?`<div class="choice-block">${btn('修改后续安排','edit-plan',t.id,'primary full')}<p>以后都换一个周期、分工或分值；保存前核对生效日期。</p></div><div class="choice-block">${btn(t.status==='paused'?'恢复这项家务':'暂时停一阵',t.status==='paused'?'resume':'pause',t.id,'full')}<p>${t.status==='paused'?'沿原日历继续，已因暂停关闭的本次不重开。':'暂时不需要做这项家务时使用，之后可以恢复。'}</p></div><details class="task-extra"><summary>更多管理操作</summary><div class="choice-block">${btn('复制为另一项家务','copy-task',t.id,'full')}<p>需要一项相似家务时使用，例如另一间卧室的床品。</p></div><div class="choice-block">${btn('以后不再安排','delete-task',t.id,'danger full')}<p>删除这项家庭家务，结束后续安排，历史打卡和积分保留。</p></div></details>`:ro()}${t.future?`<details class="task-extra"><summary>查看已确认的后续计划</summary><p>${dateLabel(t.future.first)} 起 · ${freqLabel({...t.future,plan:t.future.first})} · ${t.future.points} 分。本次保持不变。</p></details>`:''}`)}
function checkin(id,history=false){const t=history?S.missed.find(t=>t.id===+id):S.tasks.find(t=>t.id===+id);if(!t)return;modal(history?'补上这次打卡':'记录我的这份付出',`<p><strong>${esc(t.name)}</strong> · ${t.points} 分</p><div class="notice">${esc(person('me'))} · 原计划 ${dateLabel(t.plan)}。${history?'记下你当时已经做完的这一次，提交后获得 '+t.points+' 分。':'记录本人实际完成，提交后直接生效。'}</div><form id="checkin-form" data-id="${t.id}" data-history="${history}">${history?`<label class="check"><input name="attest" type="checkbox" required><span>我确认这次是我当时做完的（当时安排给：${esc(person(t.originalOwner))}）</span></label>`:''}<label>实际完成日期 · 可不填<input type="date" name="actual" value="${history?'':TODAY}" min="${JOINED}" max="${TODAY}"></label><label>一点心得 · 可不填<textarea name="note" placeholder="给今天留下一点记录"></textarea></label><label>想对伴侣说 · 可不填<textarea name="thanks" placeholder="谢谢你……"></textarea></label><p class="muted">记不清完成日期可以留空，贡献会按今天统计。</p><button class="primary full" type="submit">${history?'补上打卡':'完成打卡'} · ＋${t.points} 分</button></form>`)}
function contribution(owner,m=month){return S.records.filter(r=>r.owner===owner&&r.active&&(r.actual||r.submitted).startsWith(m))}
function balancePage(){const a=contribution('me'),b=contribution('partner'),pa=a.reduce((n,r)=>n+r.points,0),pb=b.reduce((n,r)=>n+r.points,0),total=pa+pb,share=total?Math.round(pa/total*100):null,angle=total&&!S.single?(pb-pa)/total*13:0;const months=[...new Set(['2026-09',...S.records.map(r=>(r.actual||r.submitted).slice(0,7))])].sort().reverse();return `<div class="month">${btn('‹','month-prev','','',months.indexOf(month)===months.length-1)}<select id="month" aria-label="贡献统计月份">${months.map(m=>`<option${m===month?' selected':''} value="${m}">${m.slice(0,4)} 年 ${Number(m.slice(5))} 月</option>`).join('')}</select>${btn('›','month-next','','',month===months[0])}</div><p class="muted">按北京时间自然月 · 有效家务贡献</p><div class="people"><div class="person"><div>${esc(person('me'))}</div><div class="points">${pa}<small> 分</small></div><p>${S.single?'已记录的付出':share===null?'占比 —':share+'% 的贡献'} · ${a.length} 次完成</p></div><div class="person"><div>${S.single?'等待伴侣':esc(S.partner)}</div><div class="points">${S.single?'—':pb}<small>${S.single?'':' 分'}</small></div><p>${S.single?'一起照顾家的日子':share===null?'占比 —':(100-share)+'% 的贡献'}${S.single?'':` · ${b.length} 次完成`}</p></div></div><svg class="scale" viewBox="0 0 320 160" role="img" aria-label="${S.single?'等待伴侣，暂不比较贡献':`双方贡献比例 ${share===null?'暂无':share+' 比 '+(100-share)}`}" style="color:#8a799b"><path d="M160 42V137M129 138H191" stroke="currentColor" stroke-width="4" stroke-linecap="round"/><g transform="rotate(${angle} 160 55)"><path d="M54 55H266" stroke="currentColor" stroke-width="4" stroke-linecap="round"/><circle cx="160" cy="55" r="7" fill="#654496"/><path d="M62 57L39 100H85Z" stroke="#9777b6" stroke-width="1.4" fill="none"/><path d="M258 57L235 100H281Z" stroke="#4d8e7c" stroke-width="1.4" fill="none"/><path d="M33 100Q62 135 91 100Z" fill="#d9c7ed"/><path d="M229 100Q258 135 287 100Z" fill="#b7d9cc"/></g></svg><p class="warmth">${S.single?'你的付出，已经好好记下。':total?'每一份付出，都有重量。':'这个月，还没有家务记录。'}</p><p class="muted" style="margin-top:7px">${S.single?'等伴侣加入，再一起看见彼此的贡献。':'分工可以不同，每一份付出都值得被看见。'}</p>${S.single?btn('邀请伴侣','invite','','full'):''}${section('这个月的家务记录',`<span class="muted">${a.length+b.length} 次</span>`)}${[...a,...b].sort((x,y)=>(y.actual||y.submitted).localeCompare(x.actual||x.submitted)).map(r=>`<div class="list-row"><div>${esc(r.name)}<small>${esc(person(r.owner))} · ${r.actual?dateLabel(r.actual):'未填完成日期，按记录日期统计'}</small></div><span>${r.points} 分</span></div>`).join('')||'<p class="muted">选择其他有记录的月份，或完成一件家务。</p>'}${btn('查看双方可用积分与流水　→','nav','wallet','setting-item')}`}
function recordCard(r){return `<article data-record-id="${r.id}" class="record ${!r.active?'revoked':''}"><div class="row spread"><strong>${esc(person(r.owner))} · ${esc(r.name)}</strong><span class="task-score">${r.active?'+'+r.points+' 分':'已扣回 '+r.points+' 分'}</span></div><p class="task-meta">${r.backfill?'补记 · ':''}${!r.active?'已撤销 · ':''}提交 ${dateLabel(r.submitted)} · 原定 ${dateLabel(r.plan)}<br>${r.actual?'实际完成 '+dateLabel(r.actual):'未填完成日期，按提交日期统计'}</p>${r.note?`<p>${esc(r.note)}</p>`:''}${r.thanks?`<p class="notice green">${esc(r.thanks)}</p>`:''}${r.trace.length?`<p class="trace">${r.trace.map(esc).join('<br>')}</p>`:''}<div class="row spread">${r.owner==='partner'&&r.active&&!readonly()?btn(r.heart?'♥ 已比心':'♡ 给 TA 比心','heart',r.id,'link',S.single):`<span class="muted">${r.heart?'♥ 伴侣已比心':'每一份付出都被记下'}</span>`}${r.owner==='me'&&r.active&&!readonly()?btn('修改记录','record-options',r.id,'link'):''}</div></article>`}
function journalPage(){if(journalView==='missed')return missedPage();let records=S.records.filter(r=>journalView!=='me'||r.owner==='me');return `${!readonly()?`<div class="journal-help"><strong>以前做过，忘记打卡了？</strong>${btn('补上打卡 →','missed','','link')}</div>`:''}<div class="segments">${btn('全部动态','journal-view','all',journalView==='all'?'selected':'')}${btn('我的记录','journal-view','me',journalView==='me'?'selected':'')}</div><p class="muted">按打卡时间从新到旧排列</p>${records.length?records.map(recordCard).join(''):empty('把第一份付出记在这里','完成家务后，记录和感谢都会留在这里。',btn('去看看家务','nav','tasks','primary'))}`}
function missedPage(){return `${btn('← 返回打卡记录','journal-view','all','link')}<h2>补上以前的打卡</h2><p class="muted">找到你当时已经做完、却忘记打卡的那一次。</p><div class="notice">这里只列出已经结束、没有打卡的旧安排。仍在任务大厅里的家务，请直接去那里打卡。${btn('去任务大厅','nav','tasks','link full')}</div>${S.missed.map(t=>`<div class="task"><strong>${esc(t.name)}</strong><p class="task-meta">原定 ${dateLabel(t.plan)} · 当时安排给 ${esc(person(t.originalOwner))}<br>${t.status==='done'?'已经补上打卡':t.status==='missed'?'当时没有打卡记录':esc(t.status)}</p>${btn(t.status==='done'?'已补上打卡':'我当时做过，补上打卡','backfill',t.id,'full',readonly()||t.status!=='missed')}</div>`).join('')||empty('没有可以补打卡的旧安排','仍在进行的家务，可以去任务大厅查看。')}<details class="task-extra"><summary>找不到那次家务？</summary><p>已跳过，或因暂停、删除而结束的安排不能补打卡。这里只能记录你自己当时做过的家务。</p></details>`}
function walletPage(){const owner=walletPerson,rs=S.records.filter(r=>r.owner===owner&&r.active),total=rs.reduce((n,r)=>n+r.points,0);return `<div class="segments">${btn(person('me'),'wallet-person','me',owner==='me'?'selected':'')}${!S.single?btn(S.partner,'wallet-person','partner',owner==='partner'?'selected':''):''}</div><div class="hero"><p>${S.status==='archived'?'归档钱包 · 仅供查看':'当前可用积分'}</p><div class="big">${S.wallet[owner]} <small>分</small></div><p>累计贡献 ${total} 分 · 消费不会减少贡献</p></div>${S.wallet[owner]<0?'<div class="notice">之前的打卡已更正，余额因此为负。后续完成或兑换退分会自动抵补；已有兑换继续保留。</div>':''}<p class="muted">余额是全部历史收支的结果，不随天平月份切换。双方均可查看彼此在本家庭的完整流水。</p>${section('积分流水')}${S.ledger.filter(l=>l.owner===owner).map(l=>`<div class="list-row"><div>${esc(l.title)}<small>发生于 ${dateLabel(l.date)}${l.reason?' · '+esc(l.reason):''}<br>操作后余额 ${l.balance} 分</small></div><span>${l.amount>0?'+':''}${l.amount}</span></div>`).join('')||empty('还没有积分流水','完成一件家务后，积分会记在这里。')}${btn('查看心愿与兑换记录','nav','wishes','full')}`}
function wishesPage(){const orders=S.orders.filter(o=>wishView==='history'?o.status!=='pending':o.status==='pending');return `<div class="mini-summary"><span>我的可用积分　<strong>${S.wallet.me}</strong></span>${btn('明细 →','nav','wallet','link small')}</div><div class="segments">${[['catalog','心愿目录'],['pending','待兑现'],['history','兑换历史']].map(([k,v])=>btn(v,'wish-view',k,wishView===k?'selected':'')).join('')}</div>${S.single?'<div class="notice">可以先保存心愿意向，等伴侣加入并亲自确认后再兑换。</div>':''}${wishView==='catalog'?`${S.wishes.filter(w=>w.status!=='removed').map(wishCard).join('')||empty('给生活留一点小期待','先选用一份特权建议，兑现人确认后才开放兑换。')}${btn('＋ 选用默认特权','nav','wishTemplates','full',readonly())}${btn('提出自定义心愿','new-wish','','full',readonly())}`:orders.map(orderCard).join('')||empty(wishView==='pending'?'还没有待兑现的约定':'还没有关闭的兑换','心愿目录变化不会删除已有兑换记录。',btn('看看心愿目录','wish-view','catalog','primary'))}`}
function wishCard(w){let pendingOrder=S.orders.some(o=>o.wishId===w.id&&o.buyer==='me'&&o.status==='pending');let why=S.single?'等待伴侣加入':w.provider==='me'?'由我提供，供伴侣兑换':w.status!=='open'?'兑现人尚未确认':pendingOrder?'已有待兑现':S.wallet.me<w.price?'可用积分不足':'';return `<article class="wish"><div class="row spread"><span class="pill">${({open:'已开放',pending:'待兑现人确认',off:'已下架',rejected:'未确认'})[w.status]}</span><strong style="color:var(--purple)">${w.price} 分</strong></div><h3 style="margin-top:10px">${esc(w.name)}</h3><p>${esc(w.desc)}<br>${w.provider==='unknown'?'兑现人待确定':'兑现人：'+esc(person(w.provider))}</p>${btn('查看与管理','wish-detail',w.id,'small')}${w.provider==='me'&&w.status!=='open'?btn('本人确认开放','approve-wish',w.id,'primary small',readonly()):btn(why||'兑换这份心愿',pendingOrder?'orders':'redeem',w.id,'primary small',readonly()||!!why&&!pendingOrder)}</article>`}
function orderCard(o){return `<article class="wish"><div class="row spread"><span class="order-state ${o.status!=='pending'?'closed':''}">${({pending:'待兑现',completed:'已完成',cancelled:'已取消'})[o.status]}</span><span>${o.price} 分</span></div><h3 style="margin-top:12px">${esc(o.name)}</h3><p>${esc(o.desc)}<br>兑换人：${esc(person(o.buyer))} · 兑现人：${esc(person(o.provider))}${o.removed?'<br>原心愿已移除，这笔约定继续保留。':''}</p>${o.note?`<p>约定备注：${esc(o.note)}</p>`:''}${o.trace.length?`<p class="trace">${o.trace.map(esc).join('<br>')}</p>`:''}${o.status==='pending'&&!readonly()?`<div class="row">${o.buyer==='me'?btn('盖章完成','stamp',o.id,'primary'):''}${btn('取消并退分','cancel-order',o.id,'danger')}${btn('修改备注','order-note',o.id,'link')}</div>`:''}</article>`}
function welcomePage(){return `<div class="invite-art">⌂</div><p class="step">从一个小家开始</p><div class="hero"><h3>每个人的付出，<br>都值得被看见。</h3><p>双方使用自己的账号。家务、记录和心愿，都留在你们的家庭里。</p></div>${btn('创建我的家庭','create-family','','primary full')}${btn('接受伴侣邀请','join-entry','','full')}${S.archiveSnapshot?btn('查看已归档家庭','view-archive','','link full'):''}`}
function joinPage(){return `<div class="invite-art">♡</div><div class="hero"><p>邀请你加入家庭</p><h3>阿宁的家</h3><p>邀请人：阿宁<br>你将以 ${esc(S.me)} 的本人账号加入。</p></div>${S.invitation==='expired'?'<div class="notice">这份邀请已过期，请让邀请人重新分享。过期邀请不会新增成员关系。</div>':'<p class="muted">有效邀请须在 24 小时内主动确认。家庭最多两位伴侣，已有当前家庭时不能直接加入另一家庭。</p>'}${btn('确认加入家庭','join-family','','primary full',S.invitation!=='valid'||S.status!=='none')}${btn('返回','nav','welcome','full')}`}
function settingsPage(){return `<div class="hero"><div class="row"><span class="avatar">${esc(S.me[0])}</span><div><strong>${esc(S.me)}（我）</strong><p>当前账号仅代表本人</p></div></div>${!S.single?`<div class="row" style="margin-top:16px"><span class="avatar partner">${esc(S.partner[0])}</span><div><strong>${esc(S.partner)}</strong><p>家庭成员 · 双方平等协作</p></div></div>`:''}</div>${S.single?btn('邀请伴侣加入','invite','','primary full',readonly()):''}${section('这个家的安排')}${btn('全部家务 <small>管理长期安排 →</small>','all-tasks','','setting-item')}${btn('家庭心愿 <small>内容、确认与上下架 →</small>','wish-management','','setting-item')}${btn('积分与流水 <small>双方可见 →</small>','nav','wallet','setting-item')}${btn('家庭与本人资料 <small>名称与昵称 →</small>','profile','','setting-item',readonly())}${btn('已归档家庭 <small>历史入口 →</small>','nav','history','setting-item')}${btn('日期与恢复说明 <small>操作结果 →</small>','nav','calendar','setting-item')}${ro()}${S.status==='archived'?(S.activeSnapshot?btn('返回当前家庭','return-current','','primary full'):btn('重新创建或加入家庭','start-new','','primary full')):btn('本人退出家庭','exit-family','','danger full')}<p class="muted" style="margin-top:13px">一方退出会使全家归档，双方可重新建家。原记录保留，旧家庭不能恢复。</p>`}
function historyPage(){return S.status==='archived'?`<div class="hero"><h3>${esc(S.family)}</h3><p>已归档 · 原成员可查看历史</p></div>${S.activeSnapshot?btn('返回当前家庭','return-current','','primary full'):''}${btn('查看动态记录','nav','journal','full')}${btn('查看归档钱包','nav','wallet','full')}${btn('查看兑换历史','order-history','','full')}`:S.archiveSnapshot?`<div class="hero"><h3>${esc(S.archiveSnapshot.family)}</h3><p>旧家庭历史独立保存，不会迁移到当前家庭。</p></div>${btn('打开旧家庭历史','view-archive','','full')}`:empty('还没有已归档家庭','结束协作后的家庭会保留在这里，仅原成员可查看。')}
function scheduleFields(t,prefix=''){const v=(k,defaultValue='')=>esc(t[k]??defaultValue);return `<div class="detail-grid"><label class="wide">名称<input name="${prefix}name" value="${v('name')}" required></label><label class="wide">说明<textarea name="${prefix}desc">${v('desc')}</textarea></label><label>区域<select name="${prefix}region">${regions.map((r,i)=>`<option value="${i}"${t.region===i?' selected':''}>${r}</option>`).join('')}</select></label><label>分值<select name="${prefix}points">${Array.from({length:10},(_,i)=>(i+1)*10).map(p=>`<option${t.points===p?' selected':''}>${p}</option>`).join('')}</select></label><label>分工<select name="${prefix}mode">${[['pool','公共待认领'],['me',person('me')],...(!S.single?[['partner',person('partner')],['rotate','两人轮流']]:[])].map(([k,n])=>`<option value="${k}"${t.mode===k?' selected':''}>${esc(n)}</option>`).join('')}</select></label><label>轮流首位<select name="${prefix}firstOwner"><option value="me"${t.firstOwner==='me'?' selected':''}>${esc(person('me'))}</option>${!S.single?`<option value="partner"${t.firstOwner==='partner'?' selected':''}>${esc(S.partner)}</option>`:''}</select></label><label>重复方式<select name="${prefix}freq">${[['daily','每天'],['weekly','每周指定星期'],['interval','每隔 N 天'],['monthly','每隔 N 个月'],['once','一次性']].map(([k,n])=>`<option value="${k}"${t.freq===k?' selected':''}>${n}</option>`).join('')}</select></label><label>首次日期<input name="${prefix}first" type="date" value="${v('first',t.plan||TODAY)}" min="${TODAY}" required></label><label>N（隔天 / 隔月）<input name="${prefix}every" type="number" min="1" step="1" value="${v('every',1)}"></label><label>每月指定日<input name="${prefix}day" type="number" min="1" max="31" step="1" value="${v('day',31)}"></label><label class="wide">每周星期（可多选）<div class="row">${[1,2,3,4,5,6,0].map(d=>`<label class="check small"><input type="checkbox" name="${prefix}weekdays" value="${d}"${(t.weekdays||[weekDay(t.first||t.plan||TODAY)]).includes(d)?' checked':''}><span>${'日一二三四五六'[d]}</span></label>`).join('')}</div></label></div>`}
function readSchedule(f,prefix=''){const fd=new FormData(f),g=k=>fd.get(prefix+k),t={name:g('name')?.trim(),desc:g('desc')?.trim(),region:Number(g('region')),points:Number(g('points')),mode:g('mode'),firstOwner:g('firstOwner'),freq:g('freq'),first:g('first'),every:Number(g('every')),day:Number(g('day')),weekdays:fd.getAll(prefix+'weekdays').map(Number)};if(!t.name||!t.first||t.first<TODAY)throw Error('填写名称，并选择今天或未来的首次日期。');if(t.mode==='rotate'&&(S.single||t.freq==='once'))throw Error('轮流仅适用于双人家庭的周期家务。');if(!Number.isInteger(t.every)||t.every<1)throw Error('间隔 N 必须为正整数。');if(t.freq==='weekly'&&(!t.weekdays.length||!t.weekdays.includes(weekDay(t.first))))throw Error('首次日期需符合勾选的星期。');if(t.freq==='monthly'){if(!Number.isInteger(t.day)||t.day<1||t.day>31)throw Error('每月指定日需为 1 至 31。');const d=new Date(t.first+'T00:00:00Z'),last=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate();if(Number(t.first.slice(8))!==Math.min(t.day,last))throw Error('月度首次日期须符合指定日；缺日取当月最后一天。')}return t}
function templatesPage(){return `<div class="segments add-modes" aria-label="添加方式">${btn('选择预设','add-mode','presets',addMode==='presets'?'selected':'')}${btn('自行创建','add-mode','custom',addMode==='custom'?'selected':'')}</div><section id="add-presets"${addMode==='presets'?'':' hidden'}><p class="muted">选择适合你们家的家务，可以逐项调整后再添加。</p><form id="templates-form">${templates.map(t=>{let duplicate=S.tasks.some(x=>x.source===t.source&&x.status!=='deleted');return `<div class="template"><label class="check"><input type="checkbox" name="chosen" value="${t.source}"${selected.has(t.source)?' checked':''}><span><strong>${esc(t.name)}</strong><br><span class="muted">${regions[t.region]} · ${t.points} 分${duplicate?' · 已存在，将跳过':''}</span></span></label><details><summary>核对并调整周期、分工与首次日期</summary>${scheduleFields({...t,mode:'pool'},t.source+'-')}</details></div>`}).join('')}<div class="row">${btn('全选','select-all','','link')}${btn('取消全选','select-none','','link')}</div><button class="primary full" type="submit"${readonly()?' disabled':''}>预览本次载入</button>${btn('暂时跳过，去任务大厅','nav','tasks','full')}</form></section><section id="add-custom"${addMode==='custom'?'':' hidden'}><p class="muted">为你们家添一项家务，安排首次日期和分工。</p><form id="create-task-form">${scheduleFields({name:'',desc:'',region:0,points:20,freq:'daily',mode:'pool',first:TODAY})}<button class="primary full" type="submit"${readonly()?' disabled':''}>预览并创建</button></form></section>`}
function wishTemplatesPage(){return `<p class="muted">选用只形成家庭独立心愿；兑现人亲自确认后才开放。</p>${[{source:'massage',name:'肩颈按摩 20 分钟',desc:'按摩肩颈，让紧绷的身体放松下来。',price:60},{source:'breakfast',name:'周末做一次早餐',desc:'为对方准备一顿喜欢的早餐。',price:120},{source:'quiet',name:'两小时免打扰时光',desc:'留一段读书、游戏或休息的时间。',price:80}].map(t=>`<article class="wish"><h3>${t.name}</h3><p>${t.desc}<br>建议 ${t.price} 分，可由家庭调整。</p>${btn('核对并选用','use-wish-template',t.source,'primary',readonly())}</article>`).join('')}`}
function calendarPage(){return `<p class="muted">以下为已确认规则的页面说明。具体日期可在家务详情中操作；这里只展示固定场景结果。</p>${[
 ['改本次，不改以后','9 月 13 日换床品改到 16 日：原计划仍为 13 日，本次按 16 日判断逾期，下一期仍为 20 日；不能把本次改到 20 日。'],
 ['新计划接上旧安排','保留 16 日这次，再改为每周五、首次 18 日：旧次保留至 18 日，新计划首位按原轮次接续。本次再改期最晚为 17 日。'],
 ['单项暂停后恢复','当天已经因暂停关闭的待办不重开。未生成且恰为计划日的，可以生成一次；非计划日不补发。'],
 ['家庭停用后恢复','停用前未完成待办保留；到接续日则按平台停用关闭。原单项暂停不解除，期间不补发、不记漏做。'],
 ['一次性日期已经过去','若该次从未生成，且唯一日期在暂停或停用期间过去，显示“日期已过，未生成待办”；需要时另建，不成为可补记历史。'],
 ['后一期已固定，再撤销旧完成','旧次只恢复未完成历史，不影响已认领等方式固定的后一期；仅浏览未来预览不算固定。'],
 ['月末和轮流','31 日计划遇到短月取当月末，后续月份仍按 31 日。轮流沿有效计划次序，接手、补记、更正完成日期不重排。']
 ].map(([title,text])=>`<div class="task"><h3>${title}</h3><p class="muted" style="margin-top:9px">${text}</p></div>`).join('')}${btn('返回全部家务','all-tasks','','full')}`}
function editTask(id,kind){const t=id?S.tasks.find(t=>t.id===+id):null;draft={kind,id:t?.id};if(kind==='once'){modal('仅修改本次',`<form id="once-form" data-id="${t.id}"><p class="muted">保留原计划 ${dateLabel(t.plan)}，不改变后续安排。</p><label>本次名称<input name="name" value="${esc(t.name)}" required></label><label>本次说明<textarea name="desc">${esc(t.desc)}</textarea></label><div class="detail-grid"><label>区域<select name="region">${regions.map((n,i)=>`<option value="${i}"${t.region===i?' selected':''}>${n}</option>`).join('')}</select></label><label>本次分值<select name="points">${Array.from({length:10},(_,i)=>(i+1)*10).map(n=>`<option${n===t.points?' selected':''}>${n}</option>`).join('')}</select></label></div><label>本次负责人<select name="owner">${[['pool','公共待认领'],['me',person('me')],...(!S.single?[['partner',person('partner')]]:[])].map(([k,v])=>`<option value="${k}"${t.owner===k?' selected':''}>${esc(v)}</option>`).join('')}</select></label><label>本次执行日期<input name="exec" type="date" min="${TODAY}"${t.next?` max="${plusDays(t.next,-1)}"`:''} value="${t.exec<TODAY?TODAY:t.exec}" required></label><div class="notice">${t.next?`须早于接续日期 ${dateLabel(t.next)}；最晚 ${dateLabel(plusDays(t.next,-1))}。`:'一次性，没有下一期限制。'}改期不额外占轮次。</div><button class="primary full">保存本次修改</button></form>`);return}
 const data=t?{...t,...(t.future||t.base||{}),first:kind==='copy'?TODAY:t.future?.first||t.next||TODAY,name:kind==='copy'?t.name+'（副本）':t.name}:{name:'',desc:'',region:0,points:20,freq:'daily',mode:'pool',first:TODAY};modal(kind==='new'?'创建家庭家务':kind==='copy'?'复制为独立家务':'修改后续安排',`<form id="schedule-form">${scheduleFields(data)}<p class="muted">一次性与周期不能直接互转；每周首次日须符合所选星期。</p><button class="primary full">查看保存前说明</button></form>`)}
function editWish(id=null,template=null){const w=id?S.wishes.find(w=>w.id===+id):null;const t=template?{massage:{source:'massage',name:'肩颈按摩 20 分钟',desc:'按摩肩颈，让紧绷的身体放松下来。',price:60},breakfast:{source:'breakfast',name:'周末做一次早餐',desc:'为对方准备一顿喜欢的早餐。',price:120},quiet:{source:'quiet',name:'两小时免打扰时光',desc:'留一段读书、游戏或休息的时间。',price:80}}[template]:null;const v=w||t||{name:'',desc:'',price:60};modal(w?'修改心愿':'提出一份心愿',`<form id="wish-form" data-id="${w?.id||''}" data-source="${v.source||''}"><label>心愿名称<input name="name" value="${esc(v.name)}" required></label><label>服务内容<textarea name="desc" required>${esc(v.desc)}</textarea></label><label>约定积分<input name="price" type="number" min="1" step="1" value="${v.price}" required></label><label>兑现人<select name="provider">${S.single?'<option value="unknown">等伴侣加入后再确定</option>':['partner','me'].map(p=>`<option value="${p}"${v.provider===p?' selected':''}>${p==='me'?'由我提供':'希望 '+esc(S.partner)+' 提供'}</option>`).join('')}</select></label><p class="notice">保存后等待兑现人本人确认；修改不会影响已有兑换的内容和价格。</p><button class="primary full">保存心愿</button></form>`)}
function archive(){S.status='archived';for(const o of S.orders){if(o.status==='pending'){o.status='cancelled';o.trace.push('家庭归档，兑换已取消');post(o.buyer,o.price,'家庭归档，取消兑换：'+o.name,'退回原实扣积分')}}for(const t of S.tasks){if(!t.completed&&!t.closed)t.closed='家庭已归档'}S.notices=['原记录保留，归档不可恢复，积分不迁移。']}
function setVariant(v){variant=v;const u=new URL(location.href);u.searchParams.set('variant',v);history.replaceState({},'',u);closeModal();if(page==='home'&&variant!=='B')page='tasks';else if(variant==='B'&&page==='tasks')page='home';render()}
function cycle(d){const keys=Object.keys(variants);setVariant(keys[(keys.indexOf(variant)+d+3)%3])}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action,id=b.dataset.id,t=S.tasks.find(t=>t.id===+id),w=S.wishes.find(w=>w.id===+id),o=S.orders.find(o=>o.id===+id),r=S.records.find(r=>r.id===+id);
 if(a==='close'){if(pending){toast('本次结果尚待确认，请查询后继续。');return}closeModal();return}
 if(a==='view-completion'&&S.lastCompletion){const recordId=S.lastCompletion.recordId;S.lastCompletion=null;journalView='all';go('journal');const record=document.querySelector('[data-record-id="'+recordId+'"]');if(record)$('.content').scrollTop=record.offsetTop-$('.content').offsetTop;return}if(a==='dismiss-completion'){S.lastCompletion=null;render();return}
 if(a==='nav'){closeModal();go(id);return}if(a==='variant-prev')return cycle(-1);if(a==='variant-next')return cycle(1);if(a==='reset')return reset();
 if(a==='menu')return modal('去哪里看看？',modules.map(([p,s,n])=>btn(`${s}　${n}　→`,'nav',p,'setting-item')).join('')+btn('⚙　家庭设置　→','nav','settings','setting-item'));
 if(a==='query-result'&&pending){const p=pending;pending=null;closeModal();if(p.celebrate)celebrate();render();toast('已查明：'+p.message+'。未重复执行。');return}
 if(a==='retry-read'){S.readError=false;render();return}
 if(a==='task-view'){taskView=id;render();return}if(a==='all-tasks'){taskView='all';closeModal();go('tasks');return}if(a==='clear-filters'){filters={q:'',region:'',owner:'',freq:''};render();return}if(a==='task-detail')return taskDetail(id);if(a==='adjust-instance')return adjustInstance(id);if(a==='manage-task')return manageTask(id);
 if(a==='claim'||a==='takeover')return confirmAction(a==='claim'?'认领这一次家务':'本次由我接手',`${esc(t.name)} · ${dateLabel(t.exec)}。本次负责人改为 ${esc(S.me)}，后续分工与轮次不变；${a==='claim'?'认领':'接手'}本身不获得积分。`,'confirm-owner',id,'确认'+(a==='claim'?'认领':'接手'));
 if(a==='confirm-owner')return transact(()=>{if(t.completed||t.closed)return false;t.owner='me';t.fixed=true;t.history.push(S.me+'承接本次，后续分工不变');return'已承接本次，可以本人打卡'});
 if(a==='release')return confirmAction('放回公共待认领池','只解除本次认领，双方可以重新认领，不增减积分。','confirm-release',id);
 if(a==='confirm-release')return transact(()=>{t.owner='pool';t.history.push('本人放回公共池');return'已放回公共池'});
 if(a==='checkin')return checkin(id);if(a==='backfill')return checkin(id,true);if(a==='missed'){journalView='missed';closeModal();go('journal');return}
 if(a==='journal-view'){journalView=id;render();return}if(a==='heart')return transact(()=>{r.heart=!r.heart;return r.heart?'已向伴侣比心，积分不变':'已取消比心，积分不变'});
 if(a==='record-options'){if(!r||!r.active||r.owner!=='me'||readonly())return;return modal('这条记录哪里不对？',`<p>${esc(r.name)} · ${dateLabel(r.submitted)} 打卡</p><button class="record-choice" data-action="edit-record" data-id="${r.id}"><strong>日期或文字写错了</strong><span>修改完成日期、心得或感谢，积分不变。</span></button><button class="record-choice" data-action="revoke-record" data-id="${r.id}"><strong>这次打卡记错了</strong><span>例如没有做，却误打了卡。撤销整条打卡，扣回 ${r.points} 分。</span></button>${btn('先不修改','close','','link full')}`)}
 if(a==='edit-record')return modal('修改日期或文字',`<form id="record-form" data-id="${r.id}"><p>${esc(r.name)} · ${esc(S.me)} 的打卡</p><div class="notice green">这次打卡仍然有效，积分不变。</div><label>实际完成日期 · 可不填<input type="date" name="actual" min="${JOINED}" max="${TODAY}" value="${r.actual||''}"></label><label>心得<textarea name="note">${esc(r.note)}</textarea></label><label>感谢<textarea name="thanks">${esc(r.thanks)}</textarea></label><p class="muted">改了完成日期，天平会按新日期统计；留空则按这条记录的提交日期统计。</p><button class="primary full">保存修改</button>${btn('返回选择','record-options',r.id,'link full')}</form>`);
 if(a==='revoke-record'){const task=S.tasks.find(t=>t.id===r.taskId),returns=task&&!task.closed&&!['paused','deleted'].includes(task.status)&&(!task.next||task.next>TODAY)&&!task.nextFixed&&!r.backfill;return modal('要撤销这次打卡吗？',`<form id="revoke-form" data-id="${r.id}"><p><strong>${esc(r.name)}</strong> · ${dateLabel(r.submitted)} 打卡</p><div class="notice">这次将不再算作已完成，扣回 <strong>${r.points} 分</strong>。<br>你的可用积分：${S.wallet.me} → ${S.wallet.me-r.points} 分</div><p>记录会保留并标注“已撤销”，已有的心愿兑换不受影响。</p><p class="muted">${returns?'这次家务会回到任务大厅，仍由你负责。':'这次家务不会回到任务大厅；可以补打卡的旧安排，可从“补上打卡”中重新找到。'}后面的家务安排不变。</p><label>为什么撤销？ · 必填<textarea name="reason" required placeholder="例如：选错了家务，这次其实还没做"></textarea></label><button class="full danger">撤销打卡，扣回 ${r.points} 分</button>${btn('返回选择','record-options',r.id,'link full')}</form>`)}
 if(a==='wallet-person'){walletPerson=id;render();return}if(a==='month-prev'||a==='month-next'){const ms=[...new Set(['2026-09',...S.records.map(r=>(r.actual||r.submitted).slice(0,7))])].sort().reverse();month=ms[ms.indexOf(month)+(a==='month-prev'?1:-1)]||month;render();return}
 if(a==='wish-view'){wishView=id;render();return}if(a==='orders'||a==='order-history'){wishView=a==='orders'?'pending':'history';closeModal();go('wishes');return}if(a==='wish-management'){wishView='catalog';go('wishes');return}
 if(a==='wish-detail')return modal(w.name,`<p>${esc(w.desc)}</p><div class="notice">${w.price} 分 · 兑现人 ${esc(person(w.provider))}。内容或价格修改后需兑现人重新确认，已有兑换保留原约定。</div>${!readonly()?`${btn('修改内容或价格','edit-wish',w.id,'full')}${w.provider==='me'&&w.status!=='open'?btn('本人确认开放','approve-wish',w.id,'full primary')+btn('暂不确认','reject-wish',w.id,'full'):''}${btn('下架心愿','off-wish',w.id,'full')}${btn('移除心愿','remove-wish',w.id,'full danger')}`:''}${btn('查看已有兑换','orders','','full')}`);
 if(a==='approve-wish')return confirmAction('确认我的承诺',`我确认提供「${esc(w.name)}」：${esc(w.desc)}，约定 ${w.price} 分。开放后伴侣可主动兑换，无需逐笔审批。`,'confirm-approve',id,'本人确认并开放');
 if(a==='confirm-approve')return transact(()=>{if(w.provider!=='me')return false;w.status='open';return'已确认开放，供伴侣兑换'});
 if(a==='reject-wish')return transact(()=>{w.status='rejected';return'已保留为未确认，不开放兑换'});
 if(a==='edit-wish')return editWish(id);if(a==='new-wish')return editWish();if(a==='use-wish-template')return editWish(null,id);
 if(a==='off-wish'||a==='remove-wish')return confirmAction(a==='off-wish'?'下架这份心愿':'移除这份心愿',a==='off-wish'?'停止新兑换，原兑换继续保留；兑现人确认后可重新开放。':'从目录移除且不提供恢复入口。原待兑现仍需处理，不自动取消、不退分。',a==='off-wish'?'confirm-off':'confirm-remove',id,'确认',a==='remove-wish');
 if(a==='confirm-off'||a==='confirm-remove')return transact(()=>{w.status=a==='confirm-off'?'off':'removed';if(w.status==='removed')S.orders.filter(x=>x.wishId===w.id).forEach(x=>x.removed=true);return'目录已更新，已有兑换继续保留'});
 if(a==='redeem')return confirmAction('核对这笔兑换',`<strong>${esc(w.name)}</strong><br>${esc(w.desc)}<br>兑现人：${esc(person(w.provider))}<br>扣除 ${w.price} 分，余额 ${S.wallet.me} → ${S.wallet.me-w.price} 分。<br>兑换只减少可用积分，不改变贡献。`,'confirm-redeem',id,'确认兑换');
 if(a==='confirm-redeem')return transact(()=>{if(w.status!=='open'||w.provider==='me'||S.single||S.wallet.me<w.price){error('当前不能兑换，请返回核对最新状态。');return false}if(S.orders.some(x=>x.wishId===w.id&&x.status==='pending'&&x.buyer==='me')){error('这份心愿已有待兑现记录，不重复扣分。');return false}S.orders.unshift({id:Date.now(),wishId:w.id,name:w.name,desc:w.desc,price:w.price,provider:w.provider,buyer:'me',status:'pending',note:'',trace:[]});post('me',-w.price,'兑换：'+w.name);wishView='pending';return'兑换成功，已放入待兑现'});
 if(a==='stamp')return confirmAction('已经收到这份心愿了吗？',`「${esc(o.name)}」将盖章为已完成。首版不支持撤销盖章，完成后不能取消或退分。`,'confirm-stamp',id,'我已收到，盖章完成');
 if(a==='confirm-stamp')return transact(()=>{if(o.status!=='pending'||o.buyer!=='me')return false;o.status='completed';o.trace.push('兑换人确认收到，盖章完成');return'已盖章完成，积分不变'});
 if(a==='cancel-order')return confirmAction('取消并退回原积分',`结束「${esc(o.name)}」的这笔约定，将原实扣 ${o.price} 分退回 ${esc(person(o.buyer))}。无需另一方批准；取消后不能重新打开。`,'confirm-cancel-order',id,'确认取消并退分',true);
 if(a==='confirm-cancel-order')return transact(()=>{if(o.status!=='pending')return false;o.status='cancelled';o.trace.push('家庭成员主动取消，原实扣已退回');post(o.buyer,o.price,'取消兑换：'+o.name);return`已取消，退回原实扣 ${o.price} 分`} );
 if(a==='order-note')return modal('修改约定备注',`<form id="order-note-form" data-id="${o.id}"><label>约定或延期说明 · 可不填<textarea name="note">${esc(o.note)}</textarea></label><p class="muted">修改备注不改变兑换状态，不因约定日期经过而自动完成。</p><button class="primary full">保存备注</button></form>`);
 if(a==='invite')return modal('邀请伴侣加入',`<p>家庭：${esc(S.family)}<br>邀请人：${esc(S.me)}</p><div class="notice">${S.invitation==='revoked'?'上次邀请已撤销。':'邀请有效期 24 小时，成功加入后失效。'}</div>${btn('生成并预览分享卡片','share-invite','','primary full',readonly()||!S.single)}${btn('撤销当前邀请','revoke-invite','','full',readonly()||S.invitation!=='valid')}`);
 if(a==='share-invite'){S.invitation='valid';modal('邀请卡片预览',`<div class="hero"><h3>${esc(S.me)} 邀请你加入</h3><p>${esc(S.family)} · 一起照顾家的小事<br>有效至 9 月 9 日（本原型不发送微信消息）</p></div><p class="muted">真实小程序通过微信分享。本地只展示邀请卡片；可在演示台模拟伴侣加入。</p>${btn('完成预览','close','','full')}`);renderState();return}
 if(a==='revoke-invite')return transact(()=>{S.invitation='revoked';return'当前邀请已撤销，可重新生成'});
 if(a==='partner-joins'){if(!S.single||S.status!=='active'){toast('仅单人、使用中的家庭可模拟伴侣加入。');return}S.single=false;S.invitation='used';S.notices=['伴侣已加入，你之前的记录与积分继续保留。'];render();return}
 if(a==='create-family')return modal('给这个家起个名字',`<form id="family-form"><label>家庭名称<input name="name" value="我们的家" required maxlength="30"></label><p class="muted">创建后可以先选家务，邀请伴侣稍后完成。</p><button class="primary full">创建并选择家务</button></form>`);
 if(a==='join-entry'){S.invitation='valid';go('join');return}if(a==='join-family')return transact(()=>{if(S.status!=='none'||S.invitation!=='valid')return false;S.status='active';S.single=false;S.family='阿宁的家';S.invitation='used';page='templates';return'已加入家庭'}, {allow:true});
 if(a==='profile')return modal('家庭与本人资料',`<form id="profile-form"><label>家庭名称<input name="family" value="${esc(S.family)}" required></label><label>我的昵称<input name="me" value="${esc(S.me)}" required></label><p class="muted">双方可改家庭名称，昵称仅由本人修改。</p><button class="primary full">保存资料</button></form>`);
 if(a==='exit-family')return confirmAction('退出将结束整个家庭的协作',`你和 ${S.single?'尚未加入的伴侣':esc(S.partner)} 在此家庭的协作将结束。原记录保留、家庭不可恢复。${S.orders.filter(o=>o.status==='pending').length} 笔待兑现会自动取消，原实扣退入归档钱包。负余额和未完成兑换都不阻止退出。`,'exit-step-two','','继续查看退出确认',true);
 if(a==='exit-step-two')return confirmAction('再次确认：退出并归档全家',`「${esc(S.family)}」归档后只能查看历史。双方可以重新创建或加入家庭，积分和记录不会迁移。`,'confirm-exit','','确认本人退出',true);
 if(a==='confirm-exit')return transact(()=>{archive();page='settings';return'已退出，全家归档，待兑现已取消退分'}, {allow:S.status==='disabled'});
 if(a==='return-current'&&S.activeSnapshot){const old=structuredClone({...S,activeSnapshot:undefined});S={...S.activeSnapshot,archiveSnapshot:old};go(S.status==='none'?'welcome':'settings');return}
 if(a==='start-new'&&S.activeSnapshot){toast('你正在查看旧家庭，请先返回当前家庭。');return}
 if(a==='start-new'){const archiveSnapshot=structuredClone(S);S=seed();S.records=[];S.tasks=[];S.orders=[];S.wishes=[];S.ledger=[];S.missed=[];S.wallet={me:0,partner:0};S.status='none';S.single=true;S.archiveSnapshot=archiveSnapshot;page='welcome';render();return}
 if(a==='view-archive'&&S.archiveSnapshot){S.activeSnapshot=structuredClone({...S,archiveSnapshot:undefined});const saved=S.archiveSnapshot;S={...saved,activeSnapshot:S.activeSnapshot};go('history');return}
 if(a==='platform-restores'){if(S.status!=='disabled'){toast('只有平台停用的家庭可模拟恢复；归档家庭不可恢复。');return}S.status='active';S.notices=['平台已恢复使用 · 9 月 8 日 11:00','本场景未跨接续日，停用前待办恢复；原先单独暂停的家务仍暂停。'];render();return}
 if(a==='add-task'){addMode='presets';go('templates');return}if(a==='add-mode'){addMode=id;$('#add-presets').hidden=id!=='presets';$('#add-custom').hidden=id!=='custom';document.querySelectorAll('[data-action="add-mode"]').forEach(b=>b.classList.toggle('selected',b.dataset.id===id));return}
 if(a==='new-task'){addMode='custom';go('templates');return}if(a==='edit-once')return editTask(id,'once');if(a==='edit-plan')return editTask(id,'plan');if(a==='copy-task')return editTask(id,'copy');
 if(['skip','pause','delete-task','resume'].includes(a)){const text={skip:'本次记为已跳过，不算完成、不获积分，后续周期照常。',pause:'关闭当前未完成待办并注明暂停。恢复沿原日历，不补发暂停期间任务。','delete-task':'停止后续安排，取消当前未完成待办；保留打卡、积分与历史。',resume:t.closed==='暂停关闭'?'本次曾因暂停关闭，恢复不会重开；继续下一有效计划。':`沿原日历恢复；不补发暂停期间任务。`};return confirmAction({skip:'跳过本次',pause:'暂停这项家务','delete-task':'删除家庭家务',resume:'恢复家务'}[a],text[a],'confirm-'+a,id,'确认',a==='delete-task')}
 if(['confirm-skip','confirm-pause','confirm-delete-task','confirm-resume'].includes(a))return transact(()=>{if(a==='confirm-skip'){t.closed='已跳过';t.fixed=true;t.history.push('本次已跳过，不获积分')}if(a==='confirm-pause'){t.status='paused';if(!t.completed&&!t.closed)t.closed='暂停关闭';t.history.push('单项暂停，当前关闭')}if(a==='confirm-delete-task'){t.status='deleted';if(!t.completed&&!t.closed)t.closed='删除关闭';t.history.push('已删除，历史与积分保留')}if(a==='confirm-resume'){t.status='active';t.history.push('已恢复，关闭的本次不重开');if(t.closed==='暂停关闭'){if(t.freq==='once')t.history.push('一次性原待办已关闭，需要时另建');else t.future={...(t.future||t.base||t),first:t.next||nextDate(t),note:'暂停关闭的本次保留，后续沿原日历继续'}}}return'已更新安排，历史与后续影响可在详情查看'});
 if(a==='select-all'||a==='select-none'){document.querySelectorAll('[name=chosen]').forEach(n=>{n.checked=a==='select-all';n.checked?selected.add(n.value):selected.delete(n.value)});return}
 if(a==='confirm-import')return transact(()=>{let added=0,skipped=0;for(const item of draft.items){if(S.tasks.some(t=>t.source===item.source&&t.status!=='deleted')){skipped++;continue}const t=makeTask(item);S.tasks.push(t);added++}page='tasks';taskView='current';selected.clear();return`已新增 ${added} 项，跳过同源 ${skipped} 项；原有安排未改动`});
 if(a==='confirm-schedule')return transact(()=>{const d=draft.data,old=S.tasks.find(t=>t.id===draft.id);if(draft.kind==='plan'&&old){if(old.fixed||old.completed||old.closed){old.future=d;old.next=d.first;old.history.push(`后续计划从 ${dateLabel(d.first)} 开始，本次保持不变`)}else{Object.assign(old,makeTask({...d,source:old.source},old.id));old.history.push('未固定预览随长期计划更新')}}else S.tasks.push(makeTask({...d,source:null}));page='tasks';taskView='all';return'已保存安排，本次与后续的生效范围已分别保留'});
});
function makeTask(d,id=Date.now()+Math.random()){const t={...d,id,status:'active',owner:d.mode==='rotate'?d.firstOwner:d.mode,roundOwner:d.mode==='rotate'?d.firstOwner:undefined,plan:d.first,exec:d.first,fixed:d.first<=TODAY,history:[]};t.next=nextDate(t);t.base={...d};return t}
document.addEventListener('submit',e=>{e.preventDefault();const f=e.target,fd=new FormData(f),id=f.dataset.id;try{
 if(f.id==='checkin-form'){const history=f.dataset.history==='true',t=history?S.missed.find(t=>t.id===+id):S.tasks.find(t=>t.id===+id);const actual=fd.get('actual')||null;if(actual&&(actual<JOINED||actual>TODAY)){error('实际日期不能早于加入家庭，也不能晚于今天。');return}return transact(()=>{if(S.records.some(r=>r.taskId===t.id&&r.active)||history&&t.status!=='missed'||!history&&(t.completed||t.closed||t.owner!=='me')){error('这次状态已更新，请返回查看，不能重复完成。');return false}const r={id:Date.now(),taskId:t.id,name:t.name,owner:'me',points:t.points,plan:t.plan,actual,submitted:TODAY,active:true,note:fd.get('note'),thanks:fd.get('thanks'),heart:false,trace:[],backfill:history};S.records.unshift(r);if(history)t.status='done';else{t.completed=true;t.fixed=true}post('me',t.points,(history?'补记：':'完成：')+t.name);if(history){page='journal';journalView='all'}else{page='tasks';S.lastCompletion={recordId:r.id,name:t.name,points:t.points}}return`已${history?'补记':'打卡'}，获得 ${t.points} 分`},{celebrate:true})}
 if(f.id==='record-form')return transact(()=>{const r=S.records.find(r=>r.id===+id),actual=fd.get('actual')||null;if(actual&&(actual<JOINED||actual>TODAY)){error('日期超出本人加入日至今天的范围。');return false}r.actual=actual;r.note=fd.get('note');r.thanks=fd.get('thanks');r.trace.push('已编辑：文字或实际完成日期已更正');return'记录已更新，累计贡献和可用积分不变'});
 if(f.id==='revoke-form')return transact(()=>{const r=S.records.find(r=>r.id===+id);if(!r.active||r.owner!=='me')return false;const reason=fd.get('reason').trim();if(!reason){error('请填写撤销原因。');return false}r.active=false;r.trace.push('本人已撤销：'+reason);post('me',-r.points,'撤销：'+r.name,reason);const t=S.tasks.find(t=>t.id===r.taskId),miss=S.missed.find(t=>t.id===r.taskId);if(t&&!t.closed&&!['paused','deleted'].includes(t.status)&&(!t.next||t.next>TODAY)&&!t.nextFixed&&!r.backfill){t.completed=false;t.owner='me'}else if(miss)miss.status='missed';else if(!t||!t.closed&&!['paused','deleted'].includes(t.status))S.missed.push({id:r.taskId,name:r.name,points:r.points,plan:r.plan,originalOwner:'me',status:'missed'});return'已撤销，扣回原获积分，保留原记录与比心'});
 if(f.id==='order-note-form')return transact(()=>{const o=S.orders.find(o=>o.id===+id);if(o.status!=='pending')return false;o.note=fd.get('note');o.trace.push('约定备注已编辑');return'备注已更新'});
 if(f.id==='wish-form')return transact(()=>{const provider=fd.get('provider'),source=f.dataset.source||null,w=S.wishes.find(w=>w.id===+id),dup=source&&S.wishes.find(x=>x.id!==w?.id&&x.source===source&&x.provider===provider&&x.status!=='removed');if(dup){error('已存在同源、同兑现人的心愿：'+dup.name+'。请返回目录查看已有条目，不覆盖或自动开放。');return false}const price=Number(fd.get('price'));if(!Number.isInteger(price)||price<1){error('心愿价格须为正整数。');return false}const data={name:fd.get('name').trim(),desc:fd.get('desc').trim(),price,provider,status:'pending',source};if(w)Object.assign(w,data);else S.wishes.push({...data,id:Date.now()});wishView='catalog';page='wishes';return'心愿已保存，等待兑现人本人确认'});
 if(f.id==='family-form')return transact(()=>{if(S.status!=='none'){error('已有当前家庭，不能覆盖成员关系。');return false}S.family=fd.get('name').trim();S.status='active';S.single=true;page='templates';return'家庭已创建，可以先选择家务'},{allow:true});
 if(f.id==='profile-form')return transact(()=>{S.family=fd.get('family').trim();S.me=fd.get('me').trim();return'家庭名称与本人昵称已更新'});
 if(f.id==='once-form')return transact(()=>{const t=S.tasks.find(t=>t.id===+id),date=fd.get('exec');if(date<TODAY||t.next&&date>=t.next){error('本次日期需为今天或未来，并早于接续日期。');return false}Object.assign(t,{name:fd.get('name').trim(),desc:fd.get('desc').trim(),region:Number(fd.get('region')),points:Number(fd.get('points')),owner:fd.get('owner'),exec:date,fixed:true});t.history.push('仅本次已修改；原计划与后续不变');return'已修改本次，长期安排不变'});
 if(f.id==='schedule-form'||f.id==='create-task-form'){if(f.id==='create-task-form')draft={kind:'new',origin:'inline'};const data=readSchedule(f),old=S.tasks.find(t=>t.id===draft.id);if(draft.kind==='plan'&&old){if((old.freq==='once')!==(data.freq==='once'))throw Error('一次性与周期不能直接互转，请结束旧安排后另建。');if((old.fixed||old.completed||old.closed)&&data.first<=[old.plan,old.exec,TODAY].sort().at(-1))throw Error('新计划首次日期必须晚于保留本次的原计划日期与执行日期。');if(data.mode==='rotate'&&old.mode==='rotate')data.firstOwner=old.roundOwner==='me'?'partner':'me'}draft.data=data;const next=nextDate({...data,plan:data.first});return modal('保存前核对接续安排',`<p><strong>${esc(data.name)}</strong> · ${data.points} 分</p><div class="timeline"><p>${old&&draft.kind==='plan'&&(old.fixed||old.completed||old.closed)?`保留本次：原定 ${dateLabel(old.plan)}，执行 ${dateLabel(old.exec)}，负责人 ${esc(person(old.owner))}。旧次未完成时保留至 ${dateLabel(data.first)}，届时转为历史。`:'没有需要保留的本次，新安排从首次日期开始。'}</p><p>新第一次：${dateLabel(data.first)} · ${esc(person(data.mode==='rotate'?data.firstOwner:data.mode))}</p><p>${next?`再下一次：${dateLabel(next)} · ${esc(person(data.mode==='rotate'?(data.firstOwner==='me'?'partner':'me'):data.mode))}`:'一次性，无后续重复'}</p></div><p class="muted">${freqLabel({...data,plan:data.first})}。已有打卡与历史不改写。</p>${btn('确认保存安排','confirm-schedule','','primary full')}${btn('返回修改','return-schedule','','full')}`)}
 if(f.id==='templates-form'){const sources=fd.getAll('chosen');if(!sources.length){toast('先选至少一项，或暂时跳过。');return}const items=sources.map(source=>({...readSchedule(f,source+'-'),source}));draft={items};const skipped=items.filter(d=>S.tasks.some(t=>t.source===d.source&&t.status!=='deleted'));modal('核对本次载入',`<p>将新增 ${items.length-skipped.length} 项，同源跳过 ${skipped.length} 项。应新增项目全部成功或全部不新增。</p>${items.map(d=>`<div class="list-row"><div>${esc(d.name)}<small>${skipped.includes(d)?'已存在，包括暂停项；保留家庭修改':`${freqLabel({...d,plan:d.first})} · 首次 ${dateLabel(d.first)} · ${person(d.mode==='rotate'?d.firstOwner:d.mode)} · ${d.points} 分`}</small></div></div>`).join('')}${btn('确认载入','confirm-import','','primary full')}`)}
 }catch(err){error(err.message)}});
document.addEventListener('click',e=>{if(e.target.closest('[data-action="return-schedule"]')){if(draft.origin==='inline')closeModal();else editTask(draft.id,draft.kind)}});
document.addEventListener('change',e=>{const t=e.target;if(t.id==='scenario')reset(t.value);if(t.id==='month'){month=t.value;render()}if(t.id.startsWith('filter-')){filters[t.id.slice(7)]=t.value;render()}if(t.name==='chosen')t.checked?selected.add(t.value):selected.delete(t.value)});
document.addEventListener('input',e=>{if(e.target.id==='search'){const start=e.target.selectionStart;filters.q=e.target.value;$('#task-list').innerHTML=taskList().map(taskCard).join('')||empty('没有匹配的家务','换个关键词，或清除筛选。',btn('清除筛选','clear-filters','','primary'));e.target.setSelectionRange(start,start)}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&pending){e.preventDefault();return}if(['ArrowLeft','ArrowRight'].includes(e.key)&&!e.target.closest('input,textarea,select,[contenteditable]')&&!$('#modal').open){e.preventDefault();cycle(e.key==='ArrowLeft'?-1:1)}});
$('#modal').addEventListener('cancel',e=>{if(pending)e.preventDefault()});
if(matchMedia('(max-width:800px)').matches)$('.lab').open=false;
reset();
